
services:
  telegram-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-mcp
    # Load environment variables from a .env file in the same directory
    env_file:
      - .env
    # Port mapping for SSE/HTTP transport (external:internal)
    ports:
      - "3001:8000"
    # Production SSE mode - no stdin/tty needed
    command: ["python", "main.py", "-t", "sse", "--port", "3001", "--host", "0.0.0.0"]
    restart: unless-stopped
    # Health check for production monitoring
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Optional: Uncomment for session file persistence (not recommended for production)
    # volumes:
    #   - ./telegram_sessions:/app

  # Alternative: STDIO mode for development/testing
  # Uncomment this section and comment out the above service for stdio mode
  # telegram-mcp-stdio:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: telegram-mcp-stdio
  #   env_file:
  #     - .env
  #   stdin_open: true
  #   tty: true
  #   command: ["python", "main.py", "-t", "stdio"]
  #   restart: unless-stopped 